# This is a basic workflow to help you get started with Actions

name: deploy-on-branch-created

# Controls when the workflow will run
on:
  create:
    branches: 'release/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: List files in repository root
        run: |
          echo "List File"
          ls -la
      # Runs a single command using the runners shell
      - name: Extract branch name
        id: extract_branch
        run: |
          GITHUB_REF=${{ github.ref }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Github Ref is $GITHUB_REF"
          echo "Branch Name is $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Use branch name
        run: echo "The created branch is ${{ env.BRANCH_NAME }}"
